# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[('data', 'data'), ('assets', 'assets')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc',
        'pydoc_data',
        'test',
        'werkzeug.debug',
        'werkzeug.testing',
        'click.testing',
        'pytest',
        'IPython',
        'jupyter',
        'notebook',
        'numpy',
        'pandas',
        'scipy',
        'matplotlib',
        'PIL',
        'PyQt5',
        'PyQt6',
        'setuptools',
        'distutils',
        'email.test',
        'xml.etree.cElementTree',
        'xmlrpc',
        'pdb',
        'doctest',
        'lib2to3',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='XUnity.AutoTranslator-SakuraLLM GUI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['build-assets\\app.ico'],
)
